spring.application.name=smartplan
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/smartplan
spring.datasource.username=postgres
spring.datasource.password=TSD2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
jwt.secret=smartplan_jwt_secret_key_min_32_chars_long_1234567890
jwt.expiration=86400000
